#!/usr/bin/env python
"""
Django's command-line utility for administrative tasks.

WHAT GOES HERE:
- This file is the entry point for running Django management commands.
- It sets up the Django environment and delegates to django.core.management.
- You typically do NOT modify this file; it's auto-generated by django-admin startproject.

COMMON COMMANDS:
    python manage.py runserver          # Start development server
    python manage.py migrate            # Apply database migrations
    python manage.py makemigrations     # Create migrations from model changes
    python manage.py createsuperuser    # Create admin user
    python manage.py shell              # Open Django Python shell
"""

import os
import sys


def main():
    """Run administrative tasks."""
    # Add the project root to Python path so Django can find the settings module
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
